### ISSUE TITLE
OMV 3 - Transmission - error with scheduling tab on Raspberry pi

### ISSUE THREAD

**Issue by jata1** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#1]
I use the transmission plug-in on OMV 3 on a Raspberry Pi. All working fine but there is an error when i select the scheduling tab in the plug-in settings in the GUI

The error message is... begin-hour: The value '8' is not an integer.

error details are as follows...

Error #0:exception 'OMV\Json\SchemaValidationException' with message 'begin-hour: The value '8' is not an integer.' in /usr/share/php/openmediavault/json/schema.inc:338Stack trace:#0 /usr/share/php/openmediavault/json/schema.inc(289): OMV\Json\Schema->validateInteger(8, Array, 'begin-hour')#1 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType(8, Array, 'begin-hour')#2 /usr/share/php/openmediavault/config/datamodel.inc(155): OMV\Json\Schema->validate(8, 'begin-hour')#3 /usr/share/php/openmediavault/config/configobject.inc(189): OMV\Config\DataModel->validateProperty('begin-hour', 8)#4 /usr/share/openmediavault/engined/rpc/transmissionbt.inc(416): OMV\Config\ConfigObject->set('begin-hour', 8)#5 [internal function]: OMV\Engined\Rpc\TransmissionBt->getSchedulingSettings(NULL, Array)#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)#7 /usr/share/php/openmediavault/rpc/rpc.inc(84): OMV\Rpc\ServiceAbstract->callMethod('getSchedulingSe...', NULL, Array)#8 /usr/sbin/omv-engined(516): OMV\Rpc\Rpc::call('TransmissionBt', 'getSchedulingSe...', NULL, Array, 1)#9 {main}

**Comment by ghost** [comment]
Should be fixed with 3.0.8.
