### ISSUE TITLE
Update to 2.84

### ISSUE THREAD

**Issue by anderbytes** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#10]
Please upgrade Transmission plugin version in OMV to 2.84 , as there were improvements and security fixes.

**Comment by ryecoaaron** [comment]
If you are on an amd64 system, you could download the packages from http://omv-extras.org/testing2/.  Otherwise, you will have to wait for OMV 3.x which uses Debian Jessie and includes 2.84 in the repo - https://packages.debian.org/search?keywords=transmission.

**Comment by anderbytes** [comment]
Thank you very much.
