### ISSUE TITLE
Blocklist 401 error

### ISSUE THREAD

**Issue by anderbytes** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#11]
I received an error, daily, in my email.

```
/etc/cron.daily/transmissionbt:
Unexpected response: <h1>401: Unauthorized</h1>Unauthorized Usertransmission-remote/2.82 (14160)
Host: localhost:7080
Accept: */*
Accept-Encoding: deflate, gzip
Content-Length: 30
Content-Type: application/x-www-form-urlencoded

{"method":"blocklist-update"}

run-parts: /etc/cron.daily/transmissionbt exited with return code 1
```

What it this?
Thank

**Comment by nohatssir** [comment]
It's exactly what it says, the blocklist update request is unauthorized. The only thing I can think of causing it is mismatching credentials in the cron file. Try resetting the RPC credentials in OMV.

**Comment by anderbytes** [comment]
Mismatch credentials?

Transmission daemon should just go to the internet, fetch a file, and write it locally to use it later.
I don't see what credentials are needed in that operation.

Reading about 401 error, it happens when a website (in this case, the blocklist website) asks for a password to be accessed and you type it wrong.

BUT... When I manually go to the url that I configured, I can download the blocklist file without typing anything.

And more... If I get manually inside Transmission remote GUI, I can click "Update" beside blocklist field and it updates successfully.

Strange, huh?

**Comment by nohatssir** [comment]
If you select to auto sync the blocklist a cron job will execute transmission-remote to sync the blocklist. If the script contains the wrong credentials you will get the unauthorized issue. But maybe you aren't requiring users to authenticate themselves against the RPC? Anyway, check that the credentials in /etc/cron.daily/transmissionbt is correct.

**Comment by anderbytes** [comment]
I didn't know about that file. Anyway... The credentials there are correct
=(

Don't know where to look, anymore.

**Comment by nohatssir** [comment]
Sorry, but I have too little go on to be of any help.

You could try execute the transmission-remote command as written in the file yourself (without 1>/dev/null) and see what it says.

Also, if you could post the content of `/etc/cron.daily/transmissionbt` and `/etc/transmission-daemon/settings.json` maybe that could help track down the issue. Make sure to censor passwords.

**Comment by anderbytes** [comment]
Hi @nohatssir , I´ve tested manually and reproduced the 401 error.

I understood why the script with login/password is needed.

I guess there's one thing that could crash the command: symbols in password.
I'll temporarily change my password later to a symbol-less version and try again, and post the conclusion here.

**Comment by nohatssir** [comment]
Thanks! That would make sense. If the password contains $ that would currently be parsed as an variable instead. Can you wrap the `username:password` with single quotes like this `'username:password'` and see if that helps?

**Comment by anderbytes** [comment]
Well I guess we just found the solution.

In my temporary test I used a 10-char password with chars and number.
It worked 100%

I change one of those to a symbol, then had the following results:
Works without quotes :  @ , # , % , * , _
Need quotes:  ! , $ , & , ( , )

Oddly, when I tried to mix different symbols inside the password, the single quotes haven't helped and returned me 401. But I haven't tested it much, anyway.

**MY SUGGESTION:**
After user alter / creates a password in plugin, please make a quick test to determine if the password if valid in case the blocklist is activated. Then warn user of the limitations.

**Comment by nohatssir** [comment]
Can you give an example of these characters? I'm guessing one of them is '?

**Comment by anderbytes** [comment]
No... I used $ mixed with # or @ (they weren't near each other) , don't
remember right now

**Comment by nohatssir** [comment]
I'll try and see if I can reproduce it. I'll consider this fixed if I can't.
