### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rel1ct** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#12]
3.0.1 install
Error #3003:
exception 'OMVException' with message 'Failed to get configuration (xpath=/config/services/transmissionbt)' in /usr/share/openmediavault/engined/module/transmissionbt.inc:101
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/services.inc(63): OMVModuleTransmissionBt->getStatus()
#1 [internal function]: OMVRpcServiceServices->getStatus(Array, Array)
#2 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc.inc(79): OMVRpcServiceAbstract->callMethod('getStatus', Array, Array)
#4 /usr/sbin/omv-engined(500): OMVRpc::exec('Services', 'getStatus', Array, Array, 1)
#5 {main}

dpkg --configure -a

specified directories Transmission/Download and Transmission//Torrent , other default settings.

Error #4000:
exception 'OMVException' with message 'Failed to execute command 'export LANG=C; systemctl start transmission-daemon 2>&1': Job for transmission-daemon.service failed. See 'systemctl status transmission-daemon.service' and 'journalctl -xn' for details.' in /usr/share/php/openmediavault/systemctl.inc:64
Stack trace:
#0 /usr/share/php/openmediavault/systemctl.inc(83): OMVSystemCtl->exec('start', false)
#1 /usr/share/openmediavault/engined/module/transmissionbt.inc(155): OMVSystemCtl->enable(true)
#2 /usr/share/openmediavault/engined/rpc/config.inc(206): OMVModuleTransmissionBt->startService()
#3 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#4 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#5 /usr/share/php/openmediavault/rpcservice.inc(158): OMVRpcServiceAbstract->callMethod('applyChanges', Array, Array)
#6 /usr/share/openmediavault/engined/rpc/config.inc(224): OMVRpcServiceAbstract->callMethodBg('applyChanges', Array, Array)
#7 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#8 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#9 /usr/share/php/openmediavault/rpc.inc(79): OMVRpcServiceAbstract->callMethod('applyChangesBg', Array, Array)
#10 /usr/sbin/omv-engined(500): OMVRpc::exec('Config', 'applyChangesBg', Array, Array, 1)
#11 {main}
/etc/transmission-daemon/settings.json
{
~
"download-dir": "/media/04fe3e36-17bf-4ddc-90ef-3b0bb1a00722/Transmission//Download", (//) ?
~
"incomplete-dir": "/media/04fe3e36-17bf-4ddc-90ef-3b0bb1a00722/Transmission//Torrent", (//) ?
~
"peer-limit-global": , <-- ?
"peer-limit-per-torrent": , <-- ?
~
"peer-port-random-high": , <-- ?
"peer-port-random-low": , <-- ?
"port-forwarding-enabled": , <-- ?
"peer-port-random-on-start": , <-- ?
~
}
/var/log/transmissionbt.log
Feb 11 20:07:35 SERVER transmission-daemon[31279]: [2016-02-11 20:07:35.125 MSK] JSON parse failed in /var/lib/transmission-daemon/.config/transmission-daemon/settings.json at pos 991: STRAY_TOKEN -- remaining text ",
Feb 11 20:07:35 SERVER transmission-daemon[31279]: "peer-limit-pe"
Feb 11 20:07:35 SERVER transmission-daemon[31279]: [2016-02-11 20:07:35.125 MSK] transmission-daemon Error loading config file -- exiting. (daemon.c:519)

**Comment by ryecoaaron** [comment]
That is a common problem with OMV 3.  It is not just this plugin.  That is why OMV 3 is still beta.

**Comment by rel1ct** [comment]
Why update a stable plug-in? The old version was stable at OMV3 to update the plugin to 3.0.1.
Sorry for the bad english.

**Comment by ryecoaaron** [comment]
No, having to run dpkg --configure -a is a bug in OMV not the plugin.  I get that problem on multiple systems with any plugin.  You never have to run dpkg --configure -a when installing the plugin from command line.  I have done a LOT of testing on this issue.

As for updating a stable plugin, I didn't.  nohatssir updated the code and improved/reduced the amount of code he has to maintain.  When porting to a new version of OMV, it is perfect time to make large changes that have been needed/wanted for a long time.  Some of those errors look like you need to clear your browser cache as well.

**Comment by rel1ct** [comment]
Bug plugin or OBM?

**Comment by ryecoaaron** [comment]
He fixed a small bug in the plugin but this won't fix the dpkg --configure -a bug.

**Comment by rel1ct** [comment]
JSON parse failed in /var/lib/transmission-daemon/.config/transmission-daemon/settings.json
transmission-daemon Error loading config file -- exiting

plug-in bug or am I wrong?
"Dpkg --configure -a" bug OMV, I agree.

**Comment by nohatssir** [comment]
The JSON parse error was a plugin error and the dpkg issue is an issue in OMV itself which to my knowledge hasn't been tracked down yet.
