### ISSUE TITLE
Tab "Torrents" missing

### ISSUE THREAD

**Issue by alexdaums** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#15]
Hello,

Why Torrents tab is missing in the version of OMV Erasmus plugin?

Thank you

> Erasmus

![erasmus](https://cloud.githubusercontent.com/assets/1036127/16057337/f38fbd76-3279-11e6-903e-bf0e7b9b8345.jpg)

> Stone

![stone](https://cloud.githubusercontent.com/assets/1036127/16057338/f3928cc2-3279-11e6-8658-3803f129d843.jpg)

**Comment by nohatssir** [comment]
It has been removed. There are many clients out there that does the job much better and that includes the one provided by Transmission themselves.
