### ISSUE TITLE
Some config.xml values name change

### ISSUE THREAD

**Issue by subzero79** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#16]
Some of the old plugin config.xml tags are slightly different from version 2 to 3. This could create problems during upgrade. So far i have seen an issue from a user in the IRC channel with properties. 

pxeenabled -> pxe-enabled
dhtenabled -> dht-enabled

```The property 'pexenabled' does not exist in the model 'conf.service.transmissionbt'.```

Maybe consider this in the postint file to "sed" the proper values during the OS upgrade.

**Comment by nohatssir** [comment]
The problem is that I've should have created a migration for that when it was changed which I forgot about. Now it's more or less too late I think.

**Comment by subzero79** [comment]
Ok. Ill close the issue then will keep this as reminder when upgrade comes.
