### ISSUE TITLE
403: forbidden by accessing RPC

### ISSUE THREAD

**Issue by Thanerik** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#6]
I updated transmissionBT today to 1.0.13, and I usually could enter my torrents by using Transmission Remote GUI in Windows. But now I got a 403: Forbidden error. The settings is same as before the update.

The following error is shown:
403: Forbidden
Unauthorized IP Adress.
Either disable the IP adress or add your adress to it.
If you are editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enable' entries.

Settings in OMW don't have a whitelist entry, and I tried to edit /etc/transmission-deamon/settings.json, but the file is filled with standard datas and clearly not are being using, so I don't know how to proceed.

**Comment by nohatssir** [comment]
Sorry it took so long! Kind of forgot to check the issue tracker in a while here :)

First, is this still an issue?

The whitelist settings are only available through /etc/default/openmediavault so check that file to see if you have anything related to it there.

**Comment by Thanerik** [comment]
Hi! Yes, it have been very long! No, it's not an issue anymore, I reinstalled transmissionBT and it solved the issue. I tried to avoid the reinstallation, but it wasn't possible.
