### ISSUE TITLE
Folder permissions checking

### ISSUE THREAD

**Issue by anderbytes** [OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt#9]
Hello dev.

I've had some problems with Transmission in the past, most of them because of the same cause: PERMISSIONS.

Is it possible to create some king of "checking" inside "Files and Locations" so when filled, it checks if all conditions are met?

From what I remember... debian-transmission has to be "rwx" in EVERY folder below the folder configured in Transmission, not just the final one.

Thanks.

**Comment by anderbytes** [comment]
Has this been seen, at least? 
Tnx

**Comment by ryecoaaron** [comment]
I have seen it but I don't use transmission.  I would guess this has to do with shared folder permissions.  Maybe @nohatssir can help.

**Comment by anderbytes** [comment]
I was looking also for an alternative but only transmission has a plugin.
Which do you use? You installed yours manually, correct?

**Comment by ryecoaaron** [comment]
I don't use any downloaders/file sharing programs.

**Comment by nohatssir** [comment]
To be fair, the plugin states what permissions is required, and the logs always state an permission error when the permissions aren't sufficient.

debian-transmission needs to be able to reach all parent directories and then have read, write and execute permissions on the download directory.

A permission check will maybe be added in the future, but not at the moment.

**Comment by anderbytes** [comment]
Thank you

**Comment by nohatssir** [comment]
I've implemented a plugin to the sharedfoldercombo that will check and warn for insufficient permissions in the background. It won't stop you from saving and applying your settings but it will help you see if the permissions are correct.
